name: Build and deploy to GitHub Pages
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      name: Build and deploy to GitHub Pages
        uses: actions/checkout@v2.3.1
      - name: Install, lint, build :wrench:
        run: |
          npm install
          npm run lint:js
          npm run build
      - name: Deploy :rocket:
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: build






